services:
  app:
    build:
      dockerfile_inline: |-
        FROM php:8.0.30-fpm-bullseye
        RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./keys:/var/www/html/keys
      - ./public:/var/www/html/public

  nginx:
    image: nginx:alpine
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./keys:/var/www/html/keys
      - ./public:/var/www/html/public
      - ./configs/default.conf:/etc/nginx/conf.d/default.conf
